nuadmission/application/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'application'

urlpatterns = [
    path('', views.index, name = 'application'),
    
    path('app/',include([
        path('', views.application_list, name = 'list'),
        path('<int:id>/', views.application_details, name = 'details'),
    ]))
]

nuadmission/nuadmission/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('application.urls')),
    path('admin/', admin.site.urls),
    
]

nuadmission/application/models.py
from django.db import models

# Create your models here.
class application(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def body_preview (self):
        return self.body[:50]

nuadmission/application/views.py
from .models import application
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse



# Create your views here.
def index(request):
    return HttpResponse("Hello World you are at the start point")

def application_list(request):
    application_list = application.objects.all()
    return render(request,'application/application_list.html',{ 'application_list': application_list})

def application_details(request,id):
    app = get_object_or_404(application, id=id)
    return render(request,'application/application_detail.html' ,{ 'application': app})

nuadmission/application/templates/application/application_detail.html
{% extends "application/base.html" %}
  
  {% block title %} application details {%endblock title%}
   

{% block content %} 

<h2>{{application.title }}</h2>
<pre>
    {{application.body}}
</pre>

{% endblock content%}
   

nuadmission/application/templates/application/application_list.html
{% extends "application/base.html" %}
  
  {% block title %} List view {%endblock title%}
   

{% block content %} 
<h1>Hello World !</h1>
{% for application in application_list %}

<ul>
  <a href="{% url 'application:details' application.id %}">{{application.title}}</a>
</ul>

{% empty %}
<h2>No names in the list</h2>

{% endfor %} {% endblock content%}
   
  

nuadmission/application/templates/application/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock title %}</title>
    <style>
        body{text-align: center; background-color: azure;}
    </style>
</head>
<body>
   {% block content %}
   {% endblock content%} 
</body>
</html>